name: CI for .NET Core Desktop
    
on:
  push:
    branches: 
      - master
      - develop
    paths:
      - 'StudentExamPracticeBE/**'

  pull_request:
    branches:   
      - master
      - develop
    paths:
      - 'StudentExamPracticeBE/**'
      

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./StudentExamPracticeBE
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0'

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{env.working-directory}}

    - name: Build
      run: dotnet build --configuration Release
      working-directory: ${{env.working-directory}}

    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal
      working-directory: ${{env.working-directory}}
